Knowledge graph: remove python setup code
alphagov/govuk-aws pull request #1557
Opened 2022-03-09 12:08 UTC by maxf

The Knowledge Graph instance (that we start every morning) used to do some 
data processing (like some elegibility experiments, or the brexit spreadsheet)
using Python3.7. But that version of python is no longer available on the old neo4j 
AMI we use. So we removed all python code and moved some of it to the Data Science
Data app where it belongs anyway, since that app computes most of the Knowledge Graph data already.

Since no python code is being run on the KG instance, we're removing all the python installation commands, to avoid seeing errors and keeping unnecessary code in there.

2022-03-09 12:53 UTC, rory-hurley-gds requested changes
comment out lines 19 and 20 too?

2022-03-10 08:53 UTC, exfalsoquodlibet commented on terraform/projects/app-knowledge-graph/userdata.tpl
>  sudo apt install -y python-pip
I think you do not want line 14-15
```pip install --upgrade pip```
as you are getting pip via APT now (line 17-18)
```sudo apt install -y python-pip```

2022-03-10 12:03 UTC, exfalsoquodlibet commented on terraform/projects/app-knowledge-graph/userdata.tpl
>  sudo apt install -y python-pip
Final thought, you may need 
```python3-pip``
in Linux/Ubuntu

https://stackoverflow.com/a/57266972

2022-03-10 15:28 UTC, maxf commented on terraform/projects/app-knowledge-graph/userdata.tpl
>  sudo apt install -y python-pip
I wouldn't do that at this point. The current version is indeed 2.7 but that's ok since `awscli` is pinned to a specific version. It's currently working so I'd rather not play with it, until we need to change the `awcli` version.

2022-03-10 15:55 UTC, exfalsoquodlibet approved these changes
Thanks for the changes, Max. Looks good to me.

2022-03-21 12:00 UTC, mammykins commented
Prudent changes, thanks for tidying up!

2022-03-30 09:15 UTC, exfalsoquodlibet commented
Why is this still blocked @maxf ? Do you need anything else from me / other reviewers?

2022-03-30 11:24 UTC, maxf commented
I lost track of this one, sorry. It still needs @rory-hurley-gds to approve though

2022-03-30 11:48 UTC, rory-hurley-gds approved these changes
approved

2022-03-30 11:49 UTC, rory-hurley-gds commented
Apologies - reviewed this before, but hasnt approved. should be done now

2022-03-30 13:01 UTC, merged